# Generated by Django 5.2.11 on 2026-02-22 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('machine_type', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=100)),
                ('rated_power_kw', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AIDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_decisions', to='api.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='api_aidecis_timesta_c8d7e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('power_kw', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('speed_percent', models.FloatField(blank=True, null=True)),
                ('is_on', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'machine'], name='api_sensorr_timesta_050dbd_idx')],
            },
        ),
    ]
